### ISSUE TITLE
JCenter artifacts no longer available.

### ISSUE THREAD

**Issue by williamwebb** [FlowMo7/SwaggerDSL#4]
Title.

**Comment by FlowMo7** [comment]
Hey,

I've pushed the latest artifacts (`0.2.2`) onto a new maven repository (`https://nexus.moetz.dev/repository/maven-public`). This is kinda a short term solution, I'm unfortunately not sure whether this repository will be kept, but until I'm moving to a new one, the artifact will be served there.

Sorry for the inconveniences, I'm unfortunately at the moment not actively developing this library.
